### ISSUE TITLE
Continuos build failed

### ISSUE THREAD

**Issue by gitgnarg** [JehanneOS/jehanne#11]
hch@serenity:~/src/jehanne(master)> ./hacking/devshell.sh
JehanneDEV hch@serenity ~/src/jehanne $ ./hacking/continuous-build.sh
Cannot find build tools in /home/hch/src/jehanne/hacking/bin
Removing bin/build
Removing bin/convert
Removing bin/data2c
Removing bin/elf2c
Removing bin/fetch
Removing bin/jsonpretty
Removing bin/kpdump
Removing bin/ksyscalls
Removing bin/mksys
Removing bin/op2
Removing bin/preen
Removing bin/profile
Removing bin/removemach
Removing bin/usyscalls
Removing bin/vendor
Building development tools...# golang.org/x/sys/unix
third_party/src/golang.org/x/sys/unix/ioctl.go:18: undefined: runtime.KeepAlive
third_party/src/golang.org/x/sys/unix/ioctl.go:28: undefined: runtime.KeepAlive
FAIL

**Comment by Shamar** [comment]
Hi @gitgnarg thanks for reporting.

This might be related to the version of Go you are running.  

On my Debian stretch I have
```
$ go version
go version go1.7.4 linux/amd64
```

What are your operating system and golang version?

**Comment by ojej** [comment]
gcc -DHAVE_CONFIG_H -I. -I/home/i/jehanne.TOOLCHAIN/src/binutils/ld  -I. -I/home/i/jehanne.TOOLCHAIN/src/binutils/ld -I../bfd -I/home/i/jehanne.TOOLCHAIN/src/binutils/ld/../bfd -I/home/i/jehanne.TOOLCHAIN/src/binutils/ld/../include  -g -O2 -DENABLE_PLUGINS -DLOCALEDIR="\"/posix/share/locale\""  -W -Wall -Wstrict-prototypes -Wmissing-prototypes -Wshadow -Wstack-usage=262144 -DELF_LIST_OPTIONS=TRUE -DELF_SHLIB_LIST_OPTIONS=TRUE -DELF_PLT_UNWIND_LIST_OPTIONS=TRUE -g -O2 -MT ldfile.o -MD -MP -MF .deps/ldfile.Tpo -c -o ldfile.o \
-DSCRIPTDIR='"/posix/x86_64-jehanne/lib"' -DBINDIR='"/posix/bin"' -DTOOLBINDIR='"/posix/x86_64-jehanne/bin"' \
 /home/i/jehanne.TOOLCHAIN/src/binutils/ld/ldfile.c
mv -f .deps/ldfile.Tpo .deps/ldfile.Po
make[4]: *** Brak reguł do zrobienia obiektu 'eelf_x86_64_jehanne.o', wymaganego przez 'ld-new'. Stop.
make[4]: Opuszczenie katalogu '/mnt/i/jehanne.TOOLCHAIN/build/binutils/ld'
make[3]: *** [Makefile:1762: all-recursive] Błąd 1
make[3]: Opuszczenie katalogu '/mnt/i/jehanne.TOOLCHAIN/build/binutils/ld'
make[2]: *** [Makefile:1043: all] Błąd 2
make[2]: Opuszczenie katalogu '/mnt/i/jehanne.TOOLCHAIN/build/binutils/ld'
make[1]: *** [Makefile:7175: all-ld] Błąd 2
make[1]: Opuszczenie katalogu '/mnt/i/jehanne.TOOLCHAIN/build/binutils'
make: *** [Makefile:851: all] Błąd 2
Updated 0 paths from the index

**Comment by Shamar** [comment]
Hi, [I'm moving Jehanne from GitHub](http://jehanne.h--k.it/2022/01/06/jehanne_is_moving.html), so I'm going to close all issues here.

However, the new build system (that you can find at https://gitea.it/JehanneOS/jehanne ) is not based on Go anymore, so it could finally fix your issues.
