### ISSUE TITLE
Continuous build failed

### ISSUE THREAD

**Issue by windowsEmmie** [JehanneOS/jehanne#13]
I started the build process but couldn't get farther than running `./hacking/continuous-build.sh`. Looking at the log it shows `ERROR building m4`.

I checked and golang, git, gcc, bison, binutils, and qemu are all up to date. My error is `#error "Please port gnulib freadahead.c to your platform!`(etc), and it occurs after the script enters the `jehanne/hacking/cross/src/m4/lib` directory.

The full error at the end of the log is:
```
gcc  -I.     -g -O2 -MT clean-temp.o -MD -MP -MF .deps/clean-temp.Tpo -c -o clean-temp.o clean-temp.c
mv -f .deps/clean-temp.Tpo .deps/clean-temp.Po
gcc  -I.     -g -O2 -MT freadahead.o -MD -MP -MF .deps/freadahead.Tpo -c -o freadahead.o freadahead.c
freadahead.c: In function 'freadahead':
freadahead.c:84:3: error: #error "Please port gnulib freadahead.c to your platform! Look at the definition of fflush, fread, ungetc on your system, then report this to bug-gnulib."
   84 |  #error "Please port gnulib freadahead.c to your platform! Look at the definition of fflush, fread, ungetc on your system, then report this to bug-gnulib."
      |   ^~~~~
```
`fflush`, `fread`, and `ungetc` all seem to be defined on my system.

My operating system is arch linux (x86_64), and the kernel is up to date (Linux 5.3.12-arch1-1). My go version is:
```
$ go version
go version go1.13.4 linux/amd64
```

**Comment by Shamar** [comment]
Thanks @windowsEmmie for reporting.

I'm going towards a complete refactor of the cross-compiler toolchain, moving to GCC 9.2.0.

It still need a cleanup, but I'm confident to be able to publish everything within a few weeks. This should fix these issues. I'll ask you to give a try then.

**Comment by istr** [comment]
Meanwhile you might want to have a look at https://github.com/JehanneOS/devtools/pull/7

**Comment by Shamar** [comment]
Hi @windowsEmmie, thanks to the pull request of @istr, this issue has been fixed in the current toolchain.

I was really in the process of porting GCC 9.2.0 to Jehanne, but due to the pandemic I had to change my priorities for a while.  
Now I really hope to publish the work in the next few days, but Ingo has been so kind to fix this so, if you are still interested in Jehanne, this issue is closed.
