### ISSUE TITLE
segfault starting devshell

### ISSUE THREAD

**Issue by pfr-dev** [JehanneOS/jehanne#14]
Getting a segfaut running ./devshell.sh

`david@pop-os ~/jehanne › ./hacking/devshell.sh`
`./hacking/devshell.sh: line 29: 14330 Segmentation fault      (core dumped) bash --rcfile <(cat ~/.bashrc; echo 'PS1="JehanneDEV $PS1"')`

**Comment by Ramiferous** [comment]
Nope, bashrc is fine. I'm using zsh actually, but i have bash installed and working. so strange.

**Comment by Shamar** [comment]
Hi, [I'm moving Jehanne from GitHub](http://jehanne.h--k.it/2022/01/06/jehanne_is_moving.html), so I'm going to close all issues here.

The new repository is at https://gitea.it/JehanneOS/jehanne 

Hope you'll follow Jehanne there!
