### ISSUE TITLE
raspberry pi pico 2040

### ISSUE THREAD

**Issue by ojej** [JehanneOS/jehanne#15]
This system can run on this microcontroler?
or https://tomu.im/qomu.html

**Comment by panchalnikunj** [comment]
https://www.youtube.com/channel/UCA4j-J-TFW_9Dt4iTwIjtYQ

Once visit this channel for raspberry pi pico projects.

**Comment by ojej** [comment]
qomu is fpga too ;-)

**Comment by Shamar** [comment]
Nice project Qomu, but I do not think Jehanne could run on it: its
