### ISSUE TITLE
New Home ...

### ISSUE THREAD

**Issue by drawkula** [JehanneOS/jehanne#19]
> Hi, I'm moving Jehanne from GitHub, so I'm going to close all issues here.

How can we stay uptodate via commit/issues/PR messages?
I don't see how to register there...

**Comment by Shamar** [comment]
Uhm... this is a good point.

Actually, Gitea.it is termporarily under maintainance, so they temporarily disabled the registration of new users.
This might not be a issue in the long term as [Gitea is going to join the fediverse](https://social.gitea.io/@gitea/107576791626052697).

Thinking about your issue, however, I realized that Jehanne is currently a **personal** research OS.
In these years I received only trivial contributions to documentation, and it's still NOT READY FOR PRODUCTION in any conceivable way. So setting up a contribution and coordination mechanism would be over-engineering.
Furthermore, just like more mature project [such as TuaruOS](https://github.com/klange/toaruos#are-contributions-accepted), I will not accept new third party contributions until the licencing issues are stabilized.

So ultimately, if you want to contribute to Jehanne, the best way is to contribute to [9front](https://9front.org) which is far more mature and stable. I will happily steal your work from there!
