### ISSUE TITLE
Missing build instructions on the WSL

### ISSUE THREAD

**Issue by dertuxmalwieder** [JehanneOS/jehanne#7]
FYI,

    sudo aptitude install git golang build-essential flex bison qemu-system

this is not enough for running `./continuous-build.sh` on the Windows Subsystem for Linux, running Debian Stretch. It needs `autoconf` as well. After installing that, no errors occur. :-)

**Comment by szhilkin** [comment]
I'm also installed llvm-clang (on OpenSUSE in WSL)
